language: d

d:
  - dmd
  # - dmd-2.069.0-b1 fails due to vibe.d build problems right now
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.066.1
  - gdc-4.9.2
  #- ldc-0.14.0
  - ldc-0.15.1
  - ldc-0.16.0
  - ldc-0.17.0
  - ldc-1.0.0-alpha1
